project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://isabellagarfield.github.io/Shared_Seas_Lab_Manual/" 
  repo-url: "https://github.com/IsabellaGarfield/Shared_Seas_Lab_Manual"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: images/Ray.png
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "NMFS OpenSci"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: index.qmd
        text: Home
        contents: 
          - href: content/Shared_values.qmd
            text: Shared Values
          - href: content/Collaborators.qmd
            text: Collaborators
      - href: content/Species_interest.qmd
        text: Species of Interest
      - href: content/Data_repositories.qmd
        text: Data sources
      - href: content/Hardware.Rmd
        text: Hardware
      - href: content/Field_methods.qmd
        text: Field Methods
      - href: content/Software.qmd
        text: Software
      - href: content/Products.qmd
        text: Products
      - href: content/Acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
